spring.application.name=Personal-Wealth-and-Expense-Tracker

# TiDB Cloud Configuration
# Replace <PASSWORD> with your actual TiDB database password.
# Replace <CA_PATH> with the absolute path to your downloaded CA cert file (e.g. C:/Users/isrgrootx1.pem)
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.username=cH7kaTesbGL6APQ.root
spring.datasource.password=Aaehz4kvfeyHnq5C
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# TiDB maps correctly to the standard MySQL dialect mappings in Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=${PORT:8080}
